//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeStream108.Web.Portal {
    
    
    public partial class _Default {
        
        /// <summary>
        /// categoriesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LifeStream108.Web.Portal.Controls.ToDoCategoriesControl categoriesControl;
        
        /// <summary>
        /// listsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LifeStream108.Web.Portal.Controls.ToDoListsControl listsControl;
        
        /// <summary>
        /// tasksControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LifeStream108.Web.Portal.Controls.ToDoTasksControl tasksControl;
        
        /// <summary>
        /// taskInfoControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LifeStream108.Web.Portal.Controls.ToDoTaskInfo taskInfoControl;
    }
}
